export const demoCandidates = [
  {
    id: 1,
    personal_details: {
      first_name: 'Gigi',
      last_name: 'Lee-Jo',
      gender: 'Female',
      birth_date: 'April 23, 1986 (30 yrs old)',
    },
    user_id: 2,
    position: 'C, C#',
    starting_date: null,
    location: 'Bucharest',
    is_remote: true,
    match_score: 89,
    fullName: 'Gigi Lee-Jo',
    image: 'https://i.pravatar.cc/150?u=1',
    matchingScoreColor: 'green',
  },
  {
    id: 2,
    personal_details: {
      first_name: 'Maria',
      last_name: 'Mbape',
      gender: 'Female',
      birth_date: 'April 23, 1986 (30 yrs old)',
    },
    user_id: 3,
    position: 'React.Js Developer',
    starting_date: null,
    location: 'Suceava',
    is_remote: true,
    match_score: 78,
    fullName: 'Maria Mbape',
    image: 'https://i.pravatar.cc/150?u=2',
    matchingScoreColor: 'light-orange',
  },
  {
    id: 3,
    personal_details: {
      first_name: 'Marian',
      last_name: 'Cristi',
      gender: 'Male',
      birth_date: 'April 13, 2000',
    },
    user_id: 4,
    position: 'Node.Js Developer',
    starting_date: null,
    location: 'Constanta',
    is_remote: true,
    match_score: 32,
    fullName: 'Marian Cristi',
    image: 'https://i.pravatar.cc/150?u=3',
    matchingScoreColor: 'red',
  },
  {
    id: 4,
    personal_details: {
      first_name: 'Jane',
      last_name: 'Foster',
      gender: 'Femaile',
      birth_date: 'September 1, 1998',
    },
    user_id: 1,
    position: 'Node.Js Developer',
    starting_date: null,
    location: 'Constanta',
    is_remote: true,
    match_score: 55,
    fullName: 'Jane Foster',
    image: 'https://i.pravatar.cc/150?u=4',
    matchingScoreColor: 'orange',
  },
]
